---
name: GearmanX-Worker
version: 0.02
author:
  - 'Robert Barta <rho@devc.at>'
abstract: Working class for the Gearmand job server
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Attribute::Handlers: 0
  Gearman::Client: 0
  Gearman::Worker: 0
  Test::More: 0
provides:
  GearmanX::Client:
    file: lib/GearmanX/Client.pm
    version: 0.01
  GearmanX::Serialization:
    file: lib/GearmanX/Serialization.pm
  GearmanX::Worker:
    file: lib/GearmanX/Worker.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
